### ISSUE TITLE
Plugin Won't Load

### ISSUE THREAD

**Issue by pnewell-sailthru** [msimmer/markdown-it-preview-demo#1]
I am having trouble getting a particular plugin to load.

Here is my config:

```
module.exports = {
  plugins: [
    ['markdown-it-container', {
      args: [
        'warning'
      ],
    }],
  ]
}
```
Here is my md:

```
::: warning
*here be dragons*
:::
```
What is the best way to troubleshoot?

**Comment by msimmer** [comment]
Just added a demo for this in 6199951d4e009f6ca519f7d1275862aa9c2dfc99, let me know if that clears things up!
